# NumPy(Numerical Python) 에서의 객체 지향 프로그래밍

### **class** : object를 만드는 틀
+ np.array() : 클래스 역할을 수행
+ 클래스로 생성한 객체 = 인스턴스

In [2]:
import numpy as np

# 스칼라(0차원 텐서) : 하나의 숫자
s = np.array(18.2)
s

array(18.2)

### **instance** : 속성과 메서드를 가짐
+ 속성 attibute : 객체가 가진 특징
+ 메서드 method : 객체가 가진 기능

In [3]:
# 벡터 (1차원 텐서): 숫자가 한 줄로 나열된 형태
v = np.array([92.0, 85.5, 78.2])

In [4]:
v.ndim

1

In [6]:
v.shape

(3,)

In [5]:
v.mean()

np.float64(85.23333333333333)

In [7]:
v.var()

np.float64(31.775555555555542)

# NumPy에서 차원 확인

In [12]:
import numpy as np

# 스칼라 (0차원 텐서) : 하나의 숫자
s = np.array(18.2)
print(f"스칼라 차원 : {s.ndim}, 모양: {s.shape}")
# 0, ()

# 벡터 (1차원 텐서) : 숫자가 한 줄로 나열된 형태
v = np.array([92.0, 85.5, 78.2])
print(f"벡터 차원 : {v.ndim}, 모양 : {v.shape}")
# 1, (3,)

# 행렬 (2차원 텐서) : 행과 열로 구성된 표 형태
m = np.array([[90, 80], [75, 88]])
print(f"행렬 차원 : {m.ndim}, 모양 : {m.shape}")
# 2, (2, 2)

스칼라 차원 : 0, 모양: ()
벡터 차원 : 1, 모양 : (3,)
행렬 차원 : 2, 모양 : (2, 2)


# Pandas에서 데이터 표현하기

+ Pandas DataFrame

In [14]:
import pandas as pd
import numpy as np

# 1. 기초 데이터 정의 (예제 1-2 데이터 : 3명의 학생, 2개 과목 점수)
np_matrix = np.array([
    [90, 80],
    [75, 88],
    [92, 95]
])

# 2. NumPy 배열을 Pandas DataFrame으로 변환
df = pd.DataFrame(np_matrix,
                  columns = ['통계학', '프로그래밍'],
                  index = ['1번학생', '2번학생', '3번학생'])

In [15]:
df

,통계학,프로그래밍
1번학생,90,80
2번학생,75,88
3번학생,92,95


In [16]:
df.values

array([[90, 80],
       [75, 88],
       [92, 95]])

# 벡터와 행렬의 연산

### 덧셈, 뺄셈 및 스칼라배

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [0, 1]])

# 덧셈과 스칼라배
print(f"A + B  : \n{A + B}")
print(f"3 * A : \n{3 * A}")

A + B  : 
[[2 3]
 [3 5]]
3 * A : 
[[ 3  6]
 [ 9 12]]


### 벡터에 대한 평균 및 분산 계산

In [18]:
x = np.array([92.0, 85.8, 78.2, 10.0])

mean_val = np.mean(x)  # 1/m * sum(x_i)
var_val = np.var(x)

print(f"평균: {mean_val}, 분산: {var_val}")

평균: 66.5, 분산: 1087.97


In [19]:
x.mean()

np.float64(66.5)

In [20]:
x.var()

np.float64(1087.97)

### 벡터의 내적

+ np.dot 또는 @

In [25]:
# 내적의 결과는 스칼라
v1 = np.array([1, 2])
v2 = np.array([4, 6])
dot_res = np.dot(v1, v2)
dot_res

np.int64(16)

In [27]:
print(f"v1 전치행렬: {v1.T}")
print(f"v1 행렬: {v1}")
print(f"v1 전치행렬 차원: {v1.T.shape}")
print(f"v1 행렬 차원: {v1.shape}")

v1 전치행렬: [1 2]
v1 행렬: [1 2]
v1 전치행렬 차원: (2,)
v1 행렬 차원: (2,)


In [28]:
# 전치행렬과 행렬, 구분없이 알아서 계산된다
print(f"전치행렬을 만들어서 내적 구하기: {v1.T @ v2}")
print(f"전치행렬을 만들지 않고 내적 구하기 : {v1 @ v2}")

전치행렬을 만들어서 내적 구하기: 16
전치행렬을 만들지 않고 내적 구하기 : 16


### 행렬곱
+ 원소별 곱과 구분 (* 사용)
+ np.matmul 또는 @

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [0, 1]])
np.matmul(A, B)

array([[1, 3],
       [3, 7]])

In [30]:
A @ B

array([[1, 3],
       [3, 7]])

In [31]:
A * B

array([[1, 2],
       [0, 4]])

### 벡터/행렬 구조 변환

In [34]:
# 4개의 원소를 가진 1차원 벡터를 (2, 2) 행렬로 변환

vector = np.array([92.0, 85.5, 78.2, 10.0])
matrix_2x2 = vector.reshape(2, 2)

print(f"원래 모양 : \n{vector.shape}")
print(f"변환 후 모양: \n{matrix_2x2}")

원래 모양 : 
(4,)
변환 후 모양: 
[[92.  85.5]
 [78.2 10. ]]


In [35]:
# -1를 사용하면 다른 차원에 맞춰 자동으로 크기를 결정한다
# 1차원 벡터를 (4행 1열)의 '열벡터' 모양으로 명시적 변환

column_vector = vector.reshape(-1, 1)
print(f"열벡터 변환: \n{column_vector}")
print(f"열벡터 모양: {column_vector.shape}")

열벡터 변환: 
[[92. ]
 [85.5]
 [78.2]
 [10. ]]
열벡터 모양: (4, 1)


### 전치(Transpose)와 역행렬(inverse matrix)

In [45]:
print(f"행렬 A : \n{A}")
print(f"A 전치행렬 : \n{A.T}")
print(f"A의 모양 : {A.shape}")
print()



print(f"행렬 B : \n{B}")
print(f"B 전치행렬 : \n{B.T}")
print(f"행렬 B의 역행렬: \n{np.linalg.inv(B)}")
print(f"B와 B의 역행렬의 곱 : \n{B @ np.linalg.inv(B)}")
print()

C = np.array([[1, 1], [1, 1]])
print(f"행렬 C: \n{C}")
# np.linalg.inv(C) 역행렬이 없는 경우 "LinAlgError: Singular matrix" 에러 발생

행렬 A : 
[[1 2]
 [3 4]]
A 전치행렬 : 
[[1 3]
 [2 4]]
A의 모양 : (2, 2)

행렬 B : 
[[1 1]
 [0 1]]
B 전치행렬 : 
[[1 0]
 [1 1]]
행렬 B의 역행렬: 
[[ 1. -1.]
 [ 0.  1.]]
B와 B의 역행렬의 곱 : 
[[1. 0.]
 [0. 1.]]

행렬 C: 
[[1 1]
 [1 1]]


LinAlgError: Singular matrix